name = "windpunk"
author = "possible-triangle"
version = "0.0.0-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc9f3220b8d10087eacb20a5b44f8b22ca39e470744035ca31d63d9efc5bb3d2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"

[options]
datapack-folder = "config/paxi"
release-type = "alpha"
