name = "windpunk"
author = "possible-triangle"
version = "0.0.0-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0c1950fbff371fcaa2882cc40196cf6ced56dfa0944bc47c6bca9a6d6f16418"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"

[options]
datapack-folder = "config/paxi"
release-type = "alpha"
