name = "windpunk"
author = "possible-triangle"
version = "0.0.0-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c45579b845c3aca4dd32a321495abcd01af6c6394560c62922cd260414575eec"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"

[options]
datapack-folder = "config/paxi"
release-type = "alpha"
